# This is automatically generated by the update script.
# DO NOT MANUALLY EDIT.
{
  assets-hash = "sha256-2Vpi0rZa9TbeC2Ag9LyCoa/TKbwt9bNkF0igTorRYqc=";
  edopro-version = "41.0.1";
  edopro-rev = "75b94de801d5550be78fb76171caf9e8d29a7b95";
  edopro-hash = "sha256-ChathO9mAXp5anuSb/itec0vDD+EE89Gqr+ekh4poA4=";
  irrlicht-version = "1.9.0-unstable-2025-03-30";
  irrlicht-rev = "47264fc2bc3223d110c589c9ffe4339d696a3dd0";
  irrlicht-hash = "sha256-AwUCHQOivNgSnYe8kG6JxDIz7H5PC6RoozGiOGUejTI=";
}
